# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/Software/snickerdoodle-examples/snickerdoodle/gpio/gpio.srcs/sources_1/bd/base/ip/base_auto_pc_0/base_auto_pc_0.xci
# IP: The module: 'base_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Software/snickerdoodle-examples/snickerdoodle/gpio/gpio.srcs/sources_1/bd/base/ip/base_auto_pc_0/base_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: z:/Software/snickerdoodle-examples/snickerdoodle/gpio/gpio.srcs/sources_1/bd/base/ip/base_auto_pc_0/base_auto_pc_0.xci
# IP: The module: 'base_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Software/snickerdoodle-examples/snickerdoodle/gpio/gpio.srcs/sources_1/bd/base/ip/base_auto_pc_0/base_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
