webtalk_init -webtalk_dir Z:\\Software\\snickerdoodle-examples\\snickerdoodle_GPIO\\snickerdoodle_GPIO.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2017-01-18 23:07:24" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211036957_0_0_824" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "uqfc9pg8rvh7e3l1auc5susd11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.3_20" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2694 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1484792242000" -context "sdk\\\\bsp/1484792242000"
webtalk_add_data -client sdk -key hwid -value "1480726136000" -context "sdk\\\\bsp/1484792242000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1484792242000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1484792242000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1484792242000"
webtalk_add_data -client sdk -key uid -value "1484792260000" -context "sdk\\\\application/1484792260000"
webtalk_add_data -client sdk -key hwid -value "1480726136000" -context "sdk\\\\application/1484792260000"
webtalk_add_data -client sdk -key bspid -value "1484792242000" -context "sdk\\\\application/1484792260000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1484792260000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1484792260000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1484792260000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1484792260000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1484792260000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1484792260000"
webtalk_add_data -client sdk -key projSize -value "460.9140625" -context "sdk\\\\application/1484792260000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1484809644465"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1484809644465"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1484809644465"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1484809644465"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1484809644465"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1484809644465"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1484809644465"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1484809644465"
webtalk_transmit -clientid 602818377 -regid "211036957_0_0_824" -xml Z:\\Software\\snickerdoodle-examples\\snickerdoodle_GPIO\\snickerdoodle_GPIO.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html Z:\\Software\\snickerdoodle-examples\\snickerdoodle_GPIO\\snickerdoodle_GPIO.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm Z:\\Software\\snickerdoodle-examples\\snickerdoodle_GPIO\\snickerdoodle_GPIO.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
