
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2016 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
* 
* Use of the Software is limited solely to applications:
*(a) running on a Xilinx device, or
*(b) that interact with a Xilinx device through a bus or interconnect.
*
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
*XILINX BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
*Except as contained in this notice, the name of the Xilinx shall not be used
*in advertising or otherwise to promote the sale, use or other dealings in
*this Software without prior written authorization from Xilinx.
*

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtmrctr.h"

/*
* The configuration table for devices
*/

XTmrCtr_Config XTmrCtr_ConfigTable[] =
{
	{
		XPAR_AXI_PWM_AXI_TIMER_0_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_0_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_0_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_1_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_1_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_1_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_10_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_10_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_10_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_11_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_11_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_11_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_12_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_12_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_12_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_13_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_13_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_13_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_14_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_14_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_14_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_15_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_15_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_15_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_16_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_16_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_16_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_17_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_17_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_17_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_18_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_18_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_18_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_19_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_19_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_19_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_2_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_2_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_2_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_20_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_20_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_20_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_21_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_21_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_21_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_22_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_22_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_22_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_23_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_23_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_23_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_3_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_3_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_3_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_4_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_4_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_4_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_5_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_5_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_5_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_6_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_6_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_6_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_7_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_7_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_7_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_8_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_8_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_8_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_PWM_AXI_TIMER_9_DEVICE_ID,
		XPAR_AXI_PWM_AXI_TIMER_9_BASEADDR,
		XPAR_AXI_PWM_AXI_TIMER_9_CLOCK_FREQ_HZ
	}
};


