# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.cache/wt [current_project]
set_property parent.project_path C:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files C:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/base_block_design.bd
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_processing_system7_0_0/base_block_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_rst_processing_system7_0_50M_0/base_block_design_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_rst_processing_system7_0_50M_0/base_block_design_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_rst_processing_system7_0_50M_0/base_block_design_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_4/base_block_design_axi_timer_0_4.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_4/base_block_design_axi_timer_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_5/base_block_design_axi_timer_0_5.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_5/base_block_design_axi_timer_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_6/base_block_design_axi_timer_0_6.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_6/base_block_design_axi_timer_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_7/base_block_design_axi_timer_0_7.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_7/base_block_design_axi_timer_0_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_8/base_block_design_axi_timer_0_8.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_8/base_block_design_axi_timer_0_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_9/base_block_design_axi_timer_0_9.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_9/base_block_design_axi_timer_0_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_10/base_block_design_axi_timer_0_10.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_10/base_block_design_axi_timer_0_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_11/base_block_design_axi_timer_0_11.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_11/base_block_design_axi_timer_0_11_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_12/base_block_design_axi_timer_0_12.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_12/base_block_design_axi_timer_0_12_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_13/base_block_design_axi_timer_0_13.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_13/base_block_design_axi_timer_0_13_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_14/base_block_design_axi_timer_0_14.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_14/base_block_design_axi_timer_0_14_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_15/base_block_design_axi_timer_0_15.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_15/base_block_design_axi_timer_0_15_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_16/base_block_design_axi_timer_0_16.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_16/base_block_design_axi_timer_0_16_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_17/base_block_design_axi_timer_0_17.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_17/base_block_design_axi_timer_0_17_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_18/base_block_design_axi_timer_0_18.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_18/base_block_design_axi_timer_0_18_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_19/base_block_design_axi_timer_0_19.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_19/base_block_design_axi_timer_0_19_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_20/base_block_design_axi_timer_0_20.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_20/base_block_design_axi_timer_0_20_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_21/base_block_design_axi_timer_0_21.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_21/base_block_design_axi_timer_0_21_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_22/base_block_design_axi_timer_0_22.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_22/base_block_design_axi_timer_0_22_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_23/base_block_design_axi_timer_0_23.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_23/base_block_design_axi_timer_0_23_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_24/base_block_design_axi_timer_0_24.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_24/base_block_design_axi_timer_0_24_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_25/base_block_design_axi_timer_0_25.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_25/base_block_design_axi_timer_0_25_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_26/base_block_design_axi_timer_0_26.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_26/base_block_design_axi_timer_0_26_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_27/base_block_design_axi_timer_0_27.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_axi_timer_0_27/base_block_design_axi_timer_0_27_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_xbar_0/base_block_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_tier2_xbar_0_0/base_block_design_tier2_xbar_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_tier2_xbar_1_0/base_block_design_tier2_xbar_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_tier2_xbar_2_0/base_block_design_tier2_xbar_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_tier2_xbar_3_0/base_block_design_tier2_xbar_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_auto_pc_0/base_block_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_auto_pc_1/base_block_design_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_auto_pc_2/base_block_design_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_auto_pc_3/base_block_design_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/ip/base_block_design_auto_pc_4/base_block_design_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/base_block_design_ooc.xdc]
set_property is_locked true [get_files C:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/base_block_design.bd]

read_verilog -library xil_defaultlib C:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/sources_1/bd/base_block_design/hdl/base_block_design_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/constrs_1/new/snickerdoodle_constraints.xdc
set_property used_in_implementation false [get_files C:/snickerdoodle_black_PWM/snickerdoodle_black_PWM.srcs/constrs_1/new/snickerdoodle_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top base_block_design_wrapper -part xc7z020clg400-3


write_checkpoint -force -noxdef base_block_design_wrapper.dcp

catch { report_utilization -file base_block_design_wrapper_utilization_synth.rpt -pb base_block_design_wrapper_utilization_synth.pb }
