# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/snickerdoodle_constraints.xdc

# Block Designs: bd/base_block_design/base_block_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design || ORIG_REF_NAME==base_block_design}]

# IP: bd/base_block_design/ip/base_block_design_processing_system7_0_0/base_block_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_processing_system7_0_0 || ORIG_REF_NAME==base_block_design_processing_system7_0_0}]

# IP: bd/base_block_design/ip/base_block_design_rst_processing_system7_0_50M_0/base_block_design_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==base_block_design_rst_processing_system7_0_50M_0}]

# IP: bd/base_block_design/ip/base_block_design_processing_system7_0_axi_periph_2/base_block_design_processing_system7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_processing_system7_0_axi_periph_2 || ORIG_REF_NAME==base_block_design_processing_system7_0_axi_periph_2}]

# IP: bd/base_block_design/ip/base_block_design_xbar_2/base_block_design_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_xbar_2 || ORIG_REF_NAME==base_block_design_xbar_2}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_4/base_block_design_axi_timer_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_4 || ORIG_REF_NAME==base_block_design_axi_timer_0_4}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_5/base_block_design_axi_timer_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_5 || ORIG_REF_NAME==base_block_design_axi_timer_0_5}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_6/base_block_design_axi_timer_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_6 || ORIG_REF_NAME==base_block_design_axi_timer_0_6}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_7/base_block_design_axi_timer_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_7 || ORIG_REF_NAME==base_block_design_axi_timer_0_7}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_8/base_block_design_axi_timer_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_8 || ORIG_REF_NAME==base_block_design_axi_timer_0_8}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_9/base_block_design_axi_timer_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_9 || ORIG_REF_NAME==base_block_design_axi_timer_0_9}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_10/base_block_design_axi_timer_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_10 || ORIG_REF_NAME==base_block_design_axi_timer_0_10}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_11/base_block_design_axi_timer_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_11 || ORIG_REF_NAME==base_block_design_axi_timer_0_11}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_12/base_block_design_axi_timer_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_12 || ORIG_REF_NAME==base_block_design_axi_timer_0_12}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_13/base_block_design_axi_timer_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_13 || ORIG_REF_NAME==base_block_design_axi_timer_0_13}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_14/base_block_design_axi_timer_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_14 || ORIG_REF_NAME==base_block_design_axi_timer_0_14}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_15/base_block_design_axi_timer_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_15 || ORIG_REF_NAME==base_block_design_axi_timer_0_15}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_16/base_block_design_axi_timer_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_16 || ORIG_REF_NAME==base_block_design_axi_timer_0_16}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_17/base_block_design_axi_timer_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_17 || ORIG_REF_NAME==base_block_design_axi_timer_0_17}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_18/base_block_design_axi_timer_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_18 || ORIG_REF_NAME==base_block_design_axi_timer_0_18}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_19/base_block_design_axi_timer_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_19 || ORIG_REF_NAME==base_block_design_axi_timer_0_19}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_20/base_block_design_axi_timer_0_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_20 || ORIG_REF_NAME==base_block_design_axi_timer_0_20}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_21/base_block_design_axi_timer_0_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_21 || ORIG_REF_NAME==base_block_design_axi_timer_0_21}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_22/base_block_design_axi_timer_0_22.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_22 || ORIG_REF_NAME==base_block_design_axi_timer_0_22}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_23/base_block_design_axi_timer_0_23.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_23 || ORIG_REF_NAME==base_block_design_axi_timer_0_23}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_24/base_block_design_axi_timer_0_24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_24 || ORIG_REF_NAME==base_block_design_axi_timer_0_24}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_25/base_block_design_axi_timer_0_25.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_25 || ORIG_REF_NAME==base_block_design_axi_timer_0_25}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_26/base_block_design_axi_timer_0_26.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_26 || ORIG_REF_NAME==base_block_design_axi_timer_0_26}]

# IP: bd/base_block_design/ip/base_block_design_axi_timer_0_27/base_block_design_axi_timer_0_27.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_27 || ORIG_REF_NAME==base_block_design_axi_timer_0_27}]

# IP: bd/base_block_design/ip/base_block_design_tier2_xbar_0_0/base_block_design_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_tier2_xbar_0_0 || ORIG_REF_NAME==base_block_design_tier2_xbar_0_0}]

# IP: bd/base_block_design/ip/base_block_design_tier2_xbar_1_0/base_block_design_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_tier2_xbar_1_0 || ORIG_REF_NAME==base_block_design_tier2_xbar_1_0}]

# IP: bd/base_block_design/ip/base_block_design_tier2_xbar_2_0/base_block_design_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_tier2_xbar_2_0 || ORIG_REF_NAME==base_block_design_tier2_xbar_2_0}]

# IP: bd/base_block_design/ip/base_block_design_tier2_xbar_3_0/base_block_design_tier2_xbar_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_tier2_xbar_3_0 || ORIG_REF_NAME==base_block_design_tier2_xbar_3_0}]

# IP: bd/base_block_design/ip/base_block_design_auto_pc_0/base_block_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_auto_pc_0 || ORIG_REF_NAME==base_block_design_auto_pc_0}]

# IP: bd/base_block_design/ip/base_block_design_auto_pc_1/base_block_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_auto_pc_1 || ORIG_REF_NAME==base_block_design_auto_pc_1}]

# IP: bd/base_block_design/ip/base_block_design_auto_pc_2/base_block_design_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_auto_pc_2 || ORIG_REF_NAME==base_block_design_auto_pc_2}]

# IP: bd/base_block_design/ip/base_block_design_auto_pc_3/base_block_design_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_auto_pc_3 || ORIG_REF_NAME==base_block_design_auto_pc_3}]

# IP: bd/base_block_design/ip/base_block_design_auto_pc_4/base_block_design_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_auto_pc_4 || ORIG_REF_NAME==base_block_design_auto_pc_4}]

# XDC: bd/base_block_design/ip/base_block_design_processing_system7_0_0/base_block_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_block_design_processing_system7_0_0 || ORIG_REF_NAME==base_block_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/base_block_design/ip/base_block_design_rst_processing_system7_0_50M_0/base_block_design_rst_processing_system7_0_50M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==base_block_design_rst_processing_system7_0_50M_0}]

# XDC: bd/base_block_design/ip/base_block_design_rst_processing_system7_0_50M_0/base_block_design_rst_processing_system7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==base_block_design_rst_processing_system7_0_50M_0}]

# XDC: bd/base_block_design/ip/base_block_design_rst_processing_system7_0_50M_0/base_block_design_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_xbar_2/base_block_design_xbar_2_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_4/base_block_design_axi_timer_0_4.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_4 || ORIG_REF_NAME==base_block_design_axi_timer_0_4}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_4/base_block_design_axi_timer_0_4_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_5/base_block_design_axi_timer_0_5.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_5 || ORIG_REF_NAME==base_block_design_axi_timer_0_5}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_5/base_block_design_axi_timer_0_5_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_6/base_block_design_axi_timer_0_6.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_6 || ORIG_REF_NAME==base_block_design_axi_timer_0_6}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_6/base_block_design_axi_timer_0_6_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_7/base_block_design_axi_timer_0_7.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_7 || ORIG_REF_NAME==base_block_design_axi_timer_0_7}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_7/base_block_design_axi_timer_0_7_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_8/base_block_design_axi_timer_0_8.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_8 || ORIG_REF_NAME==base_block_design_axi_timer_0_8}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_8/base_block_design_axi_timer_0_8_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_9/base_block_design_axi_timer_0_9.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_9 || ORIG_REF_NAME==base_block_design_axi_timer_0_9}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_9/base_block_design_axi_timer_0_9_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_10/base_block_design_axi_timer_0_10.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_10 || ORIG_REF_NAME==base_block_design_axi_timer_0_10}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_10/base_block_design_axi_timer_0_10_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_11/base_block_design_axi_timer_0_11.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_11 || ORIG_REF_NAME==base_block_design_axi_timer_0_11}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_11/base_block_design_axi_timer_0_11_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_12/base_block_design_axi_timer_0_12.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_12 || ORIG_REF_NAME==base_block_design_axi_timer_0_12}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_12/base_block_design_axi_timer_0_12_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_13/base_block_design_axi_timer_0_13.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_13 || ORIG_REF_NAME==base_block_design_axi_timer_0_13}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_13/base_block_design_axi_timer_0_13_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_14/base_block_design_axi_timer_0_14.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_14 || ORIG_REF_NAME==base_block_design_axi_timer_0_14}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_14/base_block_design_axi_timer_0_14_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_15/base_block_design_axi_timer_0_15.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_15 || ORIG_REF_NAME==base_block_design_axi_timer_0_15}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_15/base_block_design_axi_timer_0_15_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_16/base_block_design_axi_timer_0_16.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_16 || ORIG_REF_NAME==base_block_design_axi_timer_0_16}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_16/base_block_design_axi_timer_0_16_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_17/base_block_design_axi_timer_0_17.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_17 || ORIG_REF_NAME==base_block_design_axi_timer_0_17}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_17/base_block_design_axi_timer_0_17_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_18/base_block_design_axi_timer_0_18.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_18 || ORIG_REF_NAME==base_block_design_axi_timer_0_18}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_18/base_block_design_axi_timer_0_18_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_19/base_block_design_axi_timer_0_19.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_19 || ORIG_REF_NAME==base_block_design_axi_timer_0_19}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_19/base_block_design_axi_timer_0_19_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_20/base_block_design_axi_timer_0_20.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_20 || ORIG_REF_NAME==base_block_design_axi_timer_0_20}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_20/base_block_design_axi_timer_0_20_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_21/base_block_design_axi_timer_0_21.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_21 || ORIG_REF_NAME==base_block_design_axi_timer_0_21}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_21/base_block_design_axi_timer_0_21_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_22/base_block_design_axi_timer_0_22.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_22 || ORIG_REF_NAME==base_block_design_axi_timer_0_22}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_22/base_block_design_axi_timer_0_22_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_23/base_block_design_axi_timer_0_23.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_23 || ORIG_REF_NAME==base_block_design_axi_timer_0_23}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_23/base_block_design_axi_timer_0_23_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_24/base_block_design_axi_timer_0_24.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_24 || ORIG_REF_NAME==base_block_design_axi_timer_0_24}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_24/base_block_design_axi_timer_0_24_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_25/base_block_design_axi_timer_0_25.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_25 || ORIG_REF_NAME==base_block_design_axi_timer_0_25}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_25/base_block_design_axi_timer_0_25_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_26/base_block_design_axi_timer_0_26.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_26 || ORIG_REF_NAME==base_block_design_axi_timer_0_26}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_26/base_block_design_axi_timer_0_26_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_27/base_block_design_axi_timer_0_27.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_block_design_axi_timer_0_27 || ORIG_REF_NAME==base_block_design_axi_timer_0_27}]

# XDC: bd/base_block_design/ip/base_block_design_axi_timer_0_27/base_block_design_axi_timer_0_27_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_tier2_xbar_0_0/base_block_design_tier2_xbar_0_0_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_tier2_xbar_1_0/base_block_design_tier2_xbar_1_0_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_tier2_xbar_2_0/base_block_design_tier2_xbar_2_0_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_tier2_xbar_3_0/base_block_design_tier2_xbar_3_0_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_auto_pc_0/base_block_design_auto_pc_0_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_auto_pc_1/base_block_design_auto_pc_1_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_auto_pc_2/base_block_design_auto_pc_2_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_auto_pc_3/base_block_design_auto_pc_3_ooc.xdc

# XDC: bd/base_block_design/ip/base_block_design_auto_pc_4/base_block_design_auto_pc_4_ooc.xdc

# XDC: bd/base_block_design/base_block_design_ooc.xdc
