# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/base/base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: bd/base/ip/base_processing_system7_0_0/base_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_processing_system7_0_0 || ORIG_REF_NAME==base_processing_system7_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_gpio_0_0/base_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_gpio_0_0 || ORIG_REF_NAME==base_axi_gpio_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_iic_0_0/base_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_iic_0_0 || ORIG_REF_NAME==base_axi_iic_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_quad_spi_0_0/base_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_quad_spi_0_0 || ORIG_REF_NAME==base_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_uart16550_0_0/base_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_uart16550_0_0 || ORIG_REF_NAME==base_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_axi_periph_0/base_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0_axi_periph_0 || ORIG_REF_NAME==base_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_99M_0/base_rst_ps7_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_99M_0 || ORIG_REF_NAME==base_rst_ps7_0_99M_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_0/base_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_0 || ORIG_REF_NAME==base_xbar_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconstant_0_0/base_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconstant_0_0 || ORIG_REF_NAME==base_xlconstant_0_0} -quiet] -quiet

# IP: bd/base/ip/base_gnd_0/base_gnd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_gnd_0 || ORIG_REF_NAME==base_gnd_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_0_0/base_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconcat_0_0 || ORIG_REF_NAME==base_xlconcat_0_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_0/base_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_0 || ORIG_REF_NAME==base_auto_pc_0} -quiet] -quiet

# XDC: bd/base/base_ooc.xdc
