# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/Software/snickerdoodle-examples/snickerdoodle-black/gpio/gpio.srcs/sources_1/bd/base/ip/base_axi_gpio_0_1/base_axi_gpio_0_1.xci
# IP: The module: 'base_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Software/snickerdoodle-examples/snickerdoodle-black/gpio/gpio.srcs/sources_1/bd/base/ip/base_axi_gpio_0_1/base_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: z:/Software/snickerdoodle-examples/snickerdoodle-black/gpio/gpio.srcs/sources_1/bd/base/ip/base_axi_gpio_0_1/base_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: z:/Software/snickerdoodle-examples/snickerdoodle-black/gpio/gpio.srcs/sources_1/bd/base/ip/base_axi_gpio_0_1/base_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: z:/Software/snickerdoodle-examples/snickerdoodle-black/gpio/gpio.srcs/sources_1/bd/base/ip/base_axi_gpio_0_1/base_axi_gpio_0_1.xci
# IP: The module: 'base_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Software/snickerdoodle-examples/snickerdoodle-black/gpio/gpio.srcs/sources_1/bd/base/ip/base_axi_gpio_0_1/base_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: z:/Software/snickerdoodle-examples/snickerdoodle-black/gpio/gpio.srcs/sources_1/bd/base/ip/base_axi_gpio_0_1/base_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: z:/Software/snickerdoodle-examples/snickerdoodle-black/gpio/gpio.srcs/sources_1/bd/base/ip/base_axi_gpio_0_1/base_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
