webtalk_init -webtalk_dir C:\\snickerdoodle_black_GPIO\\snickerdoodle_black_GPIO.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May 14 15:10:41 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "vcbp98q1oikf9bs3dlcthln29a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.1_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1463263471149" -context "sdk\\\\hardware/1463263471149"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1463263471149"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1463263471149"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.1" -context "sdk\\\\hardware/1463263471149"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1463263471149"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1463263471149"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1463263471149"
webtalk_add_data -client sdk -key uid -value "1463263509610" -context "sdk\\\\bsp/1463263509610"
webtalk_add_data -client sdk -key hwid -value "1463263471149" -context "sdk\\\\bsp/1463263509610"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1463263509610"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1463263509610"
webtalk_add_data -client sdk -key uid -value "1463263543169" -context "sdk\\\\application/1463263543169"
webtalk_add_data -client sdk -key hwid -value "1463263471149" -context "sdk\\\\application/1463263543169"
webtalk_add_data -client sdk -key bspid -value "1463263509610" -context "sdk\\\\application/1463263543169"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1463263543169"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1463263543169"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1463263543169"
webtalk_transmit -clientid 2731428697 -regid "" -xml C:\\snickerdoodle_black_GPIO\\snickerdoodle_black_GPIO.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\snickerdoodle_black_GPIO\\snickerdoodle_black_GPIO.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\snickerdoodle_black_GPIO\\snickerdoodle_black_GPIO.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
